# Credit Risk Model

This project build a model to predict personal probability of default(PD), Loss given Default (LGD) and Explosure at Default (EAD) using **Logic regression** (PD) and **beta regression** (LGD&EAD)    

## Data Cleaning
The dataset contains all available data for more than 800,000 consumer loans issued from 2007 to 2015 by Lending Club: a large US peer-to-peer lending company. There are several different versions of this dataset. We have used a version available on kaggle.com. You can find it here: https://www.kaggle.com/wendykan/lending-club-loan-data/version/1

**Import required libraires**:

In [1]:
import pandas as pd
import numpy as np

##### Import Data:

In [2]:
loan_data_backup = pd.read_csv('loan_data_2007_2014.csv')
loan_data = loan_data_backup.copy()

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3437: DtypeWarning: Columns (20) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

##### Explore Data:

In [5]:
pd.options.display.max_columns = None
loan_data.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.7,9.0,f,0.0,0.0,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.4,4.0,f,0.0,0.0,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.5,10.0,f,0.0,0.0,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.0,37.0,f,0.0,0.0,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.9,38.0,f,766.9,766.9,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
loan_data.columns.values

array(['Unnamed: 0', 'id', 'member_id', 'loan_amnt', 'funded_amnt',
       'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'emp_title', 'emp_length', 'home_ownership',
       'annual_inc', 'verification_status', 'issue_d', 'loan_status',
       'pymnt_plan', 'url', 'desc', 'purpose', 'title', 'zip_code',
       'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
       'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee',
       'recoveries', 'collection_recovery_fee', 'last_pymnt_d',
       'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'policy_code', 'application_type', 'annual_inc_joint', 'dti_joint',
       'verification_status_joint', 'acc_now_delinq', 'tot_coll_amt',
       'tot_cur_bal', 'open_acc_6m', 'open_il_6m', 'open_il_12m',
       'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util',
       'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m'],
      dtype=object)

In [26]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 75 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   466285 non-null  int64
 1   id                           466285 non-null  int64
 2   member_id                    466285 non-null  int64
 3   loan_amnt                    466285 non-null  int64
 4   funded_amnt                  466285 non-null  int64
 5   funded_amnt_inv              466285 non-null  float64
 6   term                         466285 non-null  object
 7   int_rate                     466285 non-null  float64
 8   installment                  466285 non-null  float64
 9   grade                        466285 non-null  object
 10  sub_grade                    466285 non-null  object
 11  emp_title                    438697 non-null  object
 12  emp_length                   445277 non-null  object
 13  home_ownership               466285 non-null  object
 14  annual_inc                   466281 non-null  float64
 15  verification_status          466285 non-null  object
 16  issue_d                      466285 non-null  object
 17  loan_status                  466285 non-null  object
 18  pymnt_plan                   466285 non-null  object
 19  url                          466285 non-null  object
 20  desc                         125983 non-null  object
 21  purpose                      466285 non-null  object
 22  title                        466265 non-null  object
 23  zip_code                     466285 non-null  object
 24  addr_state                   466285 non-null  object
 25  dti                          466285 non-null  float64
 26  delinq_2yrs                  466256 non-null  float64
 27  earliest_cr_line             466256 non-null  object
 28  inq_last_6mths               466256 non-null  float64
 29  mths_since_last_delinq       215934 non-null  float64
 30  mths_since_last_record       62638 non-null   float64
 31  open_acc                     466256 non-null  float64
 32  pub_rec                      466256 non-null  float64
 33  revol_bal                    466285 non-null  int64
 34  revol_util                   465945 non-null  float64
 35  total_acc                    466256 non-null  float64
 36  initial_list_status          466285 non-null  object
 37  out_prncp                    466285 non-null  float64
 38  out_prncp_inv                466285 non-null  float64
 39  total_pymnt                  466285 non-null  float64
 40  total_pymnt_inv              466285 non-null  float64
 41  total_rec_prncp              466285 non-null  float64
 42  total_rec_int                466285 non-null  float64
 43  total_rec_late_fee           466285 non-null  float64
 44  recoveries                   466285 non-null  float64
 45  collection_recovery_fee      466285 non-null  float64
 46  last_pymnt_d                 465909 non-null  object
 47  last_pymnt_amnt              466285 non-null  float64
 48  next_pymnt_d                 239071 non-null  object
 49  last_credit_pull_d           466243 non-null  object
 50  collections_12_mths_ex_med   466140 non-null  float64
 51  mths_since_last_major_derog  98974 non-null   float64
 52  policy_code                  466285 non-null  int64
 53  application_type             466285 non-null  object
 54  annual_inc_joint             0 non-null       float64
 55  dti_joint                    0 non-null       float64
 56  verification_status_joint    0 non-null       float64
 57  acc_now_delinq               466256 non-null  float64
 58  tot_coll_amt                 396009 non-null  float64
 59  tot_cur_bal                  396009 non-null  float64
 60  open_acc_6m                  0 non-null       float64
 61  open_il_6m                   0 non-null       float64
 62  open_il_12m                  0 non-null       float64
 63  open_il_24m                  0 non-null       float64
 64  mths_since_rcnt_il           0 non-null       float64
 65  total_bal_il                 0 non-null       float64
 66  il_util                      0 non-null       float64
 67  open_rv_12m                  0 non-null       float64
 68  open_rv_24m                  0 non-null       float64
 69  max_bal_bc                   0 non-null       float64
 70  all_util                     0 non-null       float64
 71  total_rev_hi_lim             396009 non-null  float64
 72  inq_fi                       0 non-null       float64
 73  total_cu_tl                  0 non-null       float64
 74  inq_last_12m                 0 non-null       float64
dtypes: float64(46), int64(7), object(22)
memory usage: 266.8+ MB

## 1. Preprocess continuous variables

Remove the unnecessary text from each row then turn the remains into a numeric variable.
There are 6 continous variables to be processed, in the jupyter notebook we process 2 of them as examples:

*Emoloyment Length and Earliest Credit Date*

The full list of continous variables are processed in the python file *data_prep.py*

#### (1) Employment Length

In [16]:
loan_data['emp_length'].unique()

array(['10+ years', '< 1 year', '1 year', '3 years', '8 years', '9 years',
       '4 years', '5 years', '6 years', '2 years', '7 years', nan],
      dtype=object)

In [17]:
loan_data['emp_length_int']=loan_data['emp_length'].str.replace('\+ years','')
loan_data['emp_length_int']=loan_data['emp_length'].str.replace(' < 1 year',str(0))
loan_data['emp_length_int']=loan_data['emp_length'].str.replace('n/a',str(0))
loan_data['emp_length_int']=loan_data['emp_length'].str.replace(' years','')
loan_data['emp_length_int']=loan_data['emp_length'].str.replace(' year','')

<ipython-input-17-c930e97d8f8c>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  loan_data['emp_length_int']=loan_data['emp_length'].str.replace('\+ years','')

In [18]:
loan_data['emp_length_int'].unique()

array(['10+s', '< 1', '1', '3s', '8s', '9s', '4s', '5s', '6s', '2s', '7s',
       nan], dtype=object)

In [19]:
loan_data['emp_length_int']=loan_data['emp_length_int'].str.replace('<','')
loan_data['emp_length_int']=loan_data['emp_length_int'].str.replace('+','')
loan_data['emp_length_int']=loan_data['emp_length_int'].str.replace('s','')
loan_data['emp_length_int'].unique()

<ipython-input-19-48ce1e75c486>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  loan_data['emp_length_int']=loan_data['emp_length_int'].str.replace('+','')

array(['10', ' 1', '1', '3', '8', '9', '4', '5', '6', '2', '7', nan],
      dtype=object)

In [20]:
#convert strings to float64
loan_data['emp_length_int'] = pd.to_numeric(loan_data['emp_length_int'])

In [21]:
# check that the type for our new column is float
type(loan_data['emp_length_int'][0])

numpy.float64

#### (2) Earlist Credit Date

In [24]:
loan_data.earliest_cr_line.head()

0    Jan-85
1    Apr-99
2    Nov-01
3    Feb-96
4    Jan-96
Name: earliest_cr_line, dtype: object

In [25]:
loan_data['earliest_cr_line_date'] = pd.to_datetime(loan_data['earliest_cr_line'],format = '%b-%y')

Deal with date before 1970-01-01, so that no negative days to mess up our data

In [28]:
loan_data['earliest_cr_line_date_day'] = loan_data['earliest_cr_line_date'].apply(lambda x: (pd.to_datetime('2117-12-01')-x) if x > pd.to_datetime('2020-01-01')
                                         else (pd.to_datetime('2017-12-01')-x))
loan_data['mths_earliest_cr_line'] = round(pd.to_numeric(loan_data['earliest_cr_line_date_day']
                                                          /np.timedelta64(1,'M')))
pd.to_datetime('2117-12-01')-pd.to_datetime('2062-09-01')

Timedelta('20179 days 00:00:00')

In [29]:
# To confirm that there are no negative days
loan_data.loc[:,['earliest_cr_line','earliest_cr_line_date','earliest_cr_line_date_day','mths_earliest_cr_line']][loan_data['mths_earliest_cr_line']<0]

Empty DataFrame
Columns: [earliest_cr_line, earliest_cr_line_date, earliest_cr_line_date_day, mths_earliest_cr_line]
Index: []

## 2. PreProcessing of Discrete Variables

By looking at our data, we identifed 8 Dsicrete variables:    
*grade, sub_grade, home_ownership, verification_status, loan_status, purpose, addr_state* and *initial_list_status*

The plan is to create dummy variables for them

In [72]:
loan_data_dummies = [pd.get_dummies(loan_data['grade'], prefix = 'grade', prefix_sep = '_'),
                     pd.get_dummies(loan_data['sub_grade'], prefix = 'sub_grade', prefix_sep = '_'),
                     pd.get_dummies(loan_data['home_ownership'], prefix = 'home_ownership', prefix_sep = '_'),
                     pd.get_dummies(loan_data['verification_status'], prefix = 'verification_status', prefix_sep = '_'),
                     pd.get_dummies(loan_data['loan_status'], prefix = 'loan_status', prefix_sep = '_'),
                     pd.get_dummies(loan_data['purpose'], prefix = 'purpose', prefix_sep = '_'),
                     pd.get_dummies(loan_data['addr_state'], prefix = 'addr_state', prefix_sep = '_'),
                     pd.get_dummies(loan_data['initial_list_status'], prefix = 'initial_list_status', prefix_sep = '_')]

In [75]:
#convert to DataFrame
loan_data_dummies = pd.concat(loan_data_dummies, axis = 1)

In [76]:
loan_data = pd.concat([loan_data, loan_data_dummies],axis = 1)

## 3. Check for missing values and clean

In [77]:
# check missing value:
pd.options.display.max_rows = None
loan_data.isnull().sum()

Unnamed: 0                                                              0
id                                                                      0
member_id                                                               0
loan_amnt                                                               0
funded_amnt                                                             0
funded_amnt_inv                                                         0
term                                                                    0
int_rate                                                                0
installment                                                             0
grade                                                                   0
sub_grade                                                               0
emp_title                                                           27588
emp_length                                                          21008
home_ownership                                                          0
annual_inc                                                              4
verification_status                                                     0
issue_d                                                                 0
loan_status                                                             0
pymnt_plan                                                              0
url                                                                     0
desc                                                               340302
purpose                                                                 0
title                                                                  20
zip_code                                                                0
addr_state                                                              0
dti                                                                     0
delinq_2yrs                                                            29
earliest_cr_line                                                       29
inq_last_6mths                                                         29
mths_since_last_delinq                                             250351
mths_since_last_record                                             403647
open_acc                                                               29
pub_rec                                                                29
revol_bal                                                               0
revol_util                                                            340
total_acc                                                              29
initial_list_status                                                     0
out_prncp                                                               0
out_prncp_inv                                                           0
total_pymnt                                                             0
total_pymnt_inv                                                         0
total_rec_prncp                                                         0
total_rec_int                                                           0
total_rec_late_fee                                                      0
recoveries                                                              0
collection_recovery_fee                                                 0
last_pymnt_d                                                          376
last_pymnt_amnt                                                         0
next_pymnt_d                                                       227214
last_credit_pull_d                                                     42
collections_12_mths_ex_med                                            145
mths_since_last_major_derog                                        367311
policy_code                                                             0
application_type                                                        0
annual_inc_joint                                                   466285
dti_joint                                                          466285
verification_status_joint                                          466285
acc_now_delinq                                                         29
tot_coll_amt                                                        70276
tot_cur_bal                                                         70276
open_acc_6m                                                        466285
open_il_6m                                                         466285
open_il_12m                                                        466285
open_il_24m                                                        466285
mths_since_rcnt_il                                                 466285
total_bal_il                                                       466285
il_util                                                            466285
open_rv_12m                                                        466285
open_rv_24m                                                        466285
max_bal_bc                                                         466285
all_util                                                           466285
total_rev_hi_lim                                                    70276
inq_fi                                                             466285
total_cu_tl                                                        466285
inq_last_12m                                                       466285
last_pymnt_d_string                                                   376
last_credit_pull_d_string                                              42
earliest_cr_line_string                                                29
grade_A                                                                 0
grade_B                                                                 0
grade_C                                                                 0
grade_D                                                                 0
grade_E                                                                 0
grade_F                                                                 0
grade_G                                                                 0
sub_grade_A1                                                            0
sub_grade_A2                                                            0
sub_grade_A3                                                            0
sub_grade_A4                                                            0
sub_grade_A5                                                            0
sub_grade_B1                                                            0
sub_grade_B2                                                            0
sub_grade_B3                                                            0
sub_grade_B4                                                            0
sub_grade_B5                                                            0
sub_grade_C1                                                            0
sub_grade_C2                                                            0
sub_grade_C3                                                            0
sub_grade_C4                                                            0
sub_grade_C5                                                            0
sub_grade_D1                                                            0
sub_grade_D2                                                            0
sub_grade_D3                                                            0
sub_grade_D4                                                            0
sub_grade_D5                                                            0
sub_grade_E1                                                            0
sub_grade_E2                                                            0
sub_grade_E3                                                            0
sub_grade_E4                                                            0
sub_grade_E5                                                            0
sub_grade_F1                                                            0
sub_grade_F2                                                            0
sub_grade_F3                                                            0
sub_grade_F4                                                            0
sub_grade_F5                                                            0
sub_grade_G1                                                            0
sub_grade_G2                                                            0
sub_grade_G3                                                            0
sub_grade_G4                                                            0
sub_grade_G5                                                            0
home_ownership_ANY                                                      0
home_ownership_MORTGAGE                                                 0
home_ownership_NONE                                                     0
home_ownership_OTHER                                                    0
home_ownership_OWN                                                      0
home_ownership_RENT                                                     0
verification_status_Not Verified                                        0
verification_status_Source Verified                                     0
verification_status_Verified                                            0
loan_status_Charged Off                                                 0
loan_status_Current                                                     0
loan_status_Default                                                     0
loan_status_Does not meet the credit policy. Status:Charged Off         0
loan_status_Does not meet the credit policy. Status:Fully Paid          0
loan_status_Fully Paid                                                  0
loan_status_In Grace Period                                             0
loan_status_Late (16-30 days)                                           0
loan_status_Late (31-120 days)                                          0
purpose_car                                                             0
purpose_credit_card                                                     0
purpose_debt_consolidation                                              0
purpose_educational                                                     0
purpose_home_improvement                                                0
purpose_house                                                           0
purpose_major_purchase                                                  0
purpose_medical                                                         0
purpose_moving                                                          0
purpose_other                                                           0
purpose_renewable_energy                                                0
purpose_small_business                                                  0
purpose_vacation                                                        0
purpose_wedding                                                         0
addr_state_AK                                                           0
addr_state_AL                                                           0
addr_state_AR                                                           0
addr_state_AZ                                                           0
addr_state_CA                                                           0
addr_state_CO                                                           0
addr_state_CT                                                           0
addr_state_DC                                                           0
addr_state_DE                                                           0
addr_state_FL                                                           0
addr_state_GA                                                           0
addr_state_HI                                                           0
addr_state_IA                                                           0
addr_state_ID                                                           0
addr_state_IL                                                           0
addr_state_IN                                                           0
addr_state_KS                                                           0
addr_state_KY                                                           0
addr_state_LA                                                           0
addr_state_MA                                                           0
addr_state_MD                                                           0
addr_state_ME                                                           0
addr_state_MI                                                           0
addr_state_MN                                                           0
addr_state_MO                                                           0
addr_state_MS                                                           0
addr_state_MT                                                           0
addr_state_NC                                                           0
addr_state_NE                                                           0
addr_state_NH                                                           0
addr_state_NJ                                                           0
addr_state_NM                                                           0
addr_state_NV                                                           0
addr_state_NY                                                           0
addr_state_OH                                                           0
addr_state_OK                                                           0
addr_state_OR                                                           0
addr_state_PA                                                           0
addr_state_RI                                                           0
addr_state_SC                                                           0
addr_state_SD                                                           0
addr_state_TN                                                           0
addr_state_TX                                                           0
addr_state_UT                                                           0
addr_state_VA                                                           0
addr_state_VT                                                           0
addr_state_WA                                                           0
addr_state_WI                                                           0
addr_state_WV                                                           0
addr_state_WY                                                           0
initial_list_status_f                                                   0
initial_list_status_w                                                   0
dtype: int64

We then identified a few columns that will be crucial for our model building process, including:    
*annual_inc, deling_2yrs, inq_last_6mths, open_acc, pub_rec, total_acc,acc_now_deling, total_rev_hi_lim, emp_length_int, mths_since_earlierest_cr_Line*

In [32]:
loan_data['total_rev_hi_lim'].fillna(loan_data['funded_amnt'], inplace = True)

In [34]:
# for annual_inc, use the mean of non-missing values to replace
avg_annual_inc = loan_data['annual_inc'].mean()
loan_data['annual_inc'].fillna(avg_annual_inc, inplace = True)

In [41]:
# for all other variables, use 0 to replace 
loan_data['delinq_2yrs'].fillna(0.0, inplace = True)
loan_data['inq_last_6mths'].fillna(0, inplace = True)
loan_data['open_acc'].fillna(0, inplace = True)
loan_data['total_acc'].fillna(0, inplace = True)
loan_data['acc_now_delinq'].fillna(0.0, inplace = True)
loan_data['emp_length_int'].fillna(0, inplace = True)

##  4. Save Cleaned Data

In [ ]:
loan_data.to_csv('loan_data_2007_2014-clean.csv')